title:            "blog.condesire.com"
url:              http://blog.condesire.com
permalink:        pretty
highlighter:      pygments
markdown:         kramdown
google_analytics: UA-49755179-1
timezone:         Asia/Tokyo
port: 5000
gems:
  - jemoji
  - jekyll-mentions

destination: ../result


kramdown:
  syntax_highlighter: coderay
  enable_coderay: true
  syntax_highlighter_opts:
#    line_numbers: nil
#    line_numbers_start: 1
#    tab_width: 4
#    bold_every: 10
#    css: class
